-- Migración: módulo de Clientes Mayoristas (CRM de seguimiento)
-- Ejecutar una sola vez en: Supabase Dashboard → SQL Editor → New query → pegar y Run
-- (no se puede hacer DDL desde el backend: PostgREST no lo permite)

-- Clientes mayoristas. gm_client_id null = alta manual (no existe en GM).
create table wholesale_clients (
  id bigint generated by default as identity primary key,
  gm_client_id bigint unique,
  name text not null,
  phone text,
  phone_normalized text,
  email text,
  notes text,                              -- nota general y permanente del cliente
  tags text[] not null default '{}',
  assigned_to text,                        -- vendedor responsable
  next_contact_date date,                  -- desnormalizado del último contacto, para ordenar la agenda
  last_contact_date date,                  -- idem, para no recalcular en cada listado
  sales_synced_at timestamptz,             -- null = pendiente de backfill de ventas
  status text not null default 'active',   -- 'active' | 'archived'
  created_at timestamptz not null default now()
);

create index wholesale_clients_next_idx on wholesale_clients (next_contact_date);
create index wholesale_clients_gm_idx on wholesale_clients (gm_client_id);

-- Timeline de contactos. Nunca se borra automáticamente.
create table wholesale_contacts (
  id bigint generated by default as identity primary key,
  wholesale_client_id bigint not null references wholesale_clients(id) on delete cascade,
  contacted_at date not null,
  note text,
  outcome text,          -- 'compro' | 'va_a_comprar' | 'pidio_info' | 'no_contesta' | 'no_interesa'
  next_contact_date date,
  seller text,
  created_at timestamptz not null default now()
);

create index wholesale_contacts_client_idx on wholesale_contacts (wholesale_client_id, contacted_at desc);

-- Espejo de ventas de GM de los mayoristas. Solo totales (sin líneas de producto).
-- El id es el id de la venta en GM: PK sin identity, para poder hacer upsert y que
-- re-sincronizar no duplique nada.
create table wholesale_sales (
  id bigint primary key,
  gm_client_id bigint not null,
  date_sale date,
  items_sold int,          -- unidades vendidas en esa venta
  total_price numeric,
  channel_id bigint,
  channel text,
  store_id bigint,
  store text,
  synced_at timestamptz not null default now()
);

create index wholesale_sales_client_idx on wholesale_sales (gm_client_id, date_sale desc);

-- Estado del sync de ventas: una sola fila (id = 1). Mismo patrón que gm_sync_state.
create table wholesale_sync_state (
  id smallint primary key default 1,
  status text not null default 'idle',   -- 'idle' | 'running' | 'error'
  page int not null default 0,
  total_pages int not null default 0,
  sales_scanned int not null default 0,
  sales_saved int not null default 0,
  range_from date,
  range_to date,
  last_synced_to date,                   -- hasta qué fecha llegó el último sync exitoso
  started_at timestamptz,
  finished_at timestamptz,
  error text
);

insert into wholesale_sync_state (id) values (1);

-- Configuración del módulo: una sola fila (id = 1).
create table wholesale_settings (
  id smallint primary key default 1,
  warn_days int not null default 30,     -- semáforo ámbar: días sin comprar
  alert_days int not null default 60,    -- semáforo rojo
  history_months int not null default 12,
  sellers text[] not null default '{}'
);

insert into wholesale_settings (id) values (1);

-- RLS activado sin políticas: solo el backend (service_role key) puede leer/escribir.
alter table wholesale_clients enable row level security;
alter table wholesale_contacts enable row level security;
alter table wholesale_sales enable row level security;
alter table wholesale_sync_state enable row level security;
alter table wholesale_settings enable row level security;
